### ISSUE TITLE
Deprecate Profile Version of cu_newsletter_bundle

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1059]
## Context
There are currently two versions of cu_newsletter_bundle.
https://github.com/CuBoulder/cu_newsletter_bundle
https://github.com/CuBoulder/express/tree/dev/modules/custom/cu_newsletter_bundle

The modules in the Express repo have help links, and the code looks to be updated more recently than the custom bundle.  

## Expected result
Only one cu_newsletter_bundle exists in the Express codebase/ecosystem. 

## Possible Fix
Remove cu_newsletter_bundle and associated modules from the main Express repo. Make sure any updates, like help links, make the transition over.

**Comment by kreynen** [comment]
This is actually a blocker to releasing 2.4.0 since the bundle is no longer ignored and shows up for everyone in the core list if it is also being added with the request_bundles tag

8 sites are reporting that they have newsletter nodes https://osr-atlas03.int.colorado.edu/statistics?where={%22nodes_other%22:{%22$regex%22:%22newsletter%22,%22$options%22:%22i%22}}&projection={%22site%22:1}

Launched:
chbe
postdoctoralaffairs
asmagazine
today
education
isss

Unlaunched:
p1f4bca2b935
p15a75c78bd6

**Comment by kreynen** [comment]
Webcentral has a newsletter node and it shows up in https://www.colorado.edu/webcentral/admin/config/development/atlas/statistics
but not in https://osr-atlas03.int.colorado.edu/statistics/589a3467926f5b488b755ea8 (the id of the current stats object)
