### ISSUE TITLE
cu_rss_block - PHP exception when feed contains invalid XML

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#1068]
## Context

In cu_rss_block, we [validate the feed when the bean is created](https://github.com/CuBoulder/express/blob/dev/modules/custom/cu_rss_block/cu_rss_block.module#L30), but we don't ever check again. If the feed becomes corrupted we get a PHP exception.

## Process

1. Login to site as a SO
1. Create an RSS block with a valid feed
1. Render the bean
1. Break the feed
1. Render the bean

## Expected result

Error message indicating that the feed is not valid

## Current result

PHP exception from https://github.com/CuBoulder/express/blob/dev/modules/custom/cu_rss_block/cu_rss_block.module#L65

```
Exception: Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /data/code/profiles/express/express-2.3.5/modules/custom/cu_rss_block/cu_rss_block.module:72
in SimpleXMLElement::__construct called at /data/code/profiles/express/express-2.3.5/modules/custom/cu_rss_block/cu_rss_block.module (72)
in cu_rss_block_preprocess_entity called at /data/code/cores/drupal/drupal-7.54/includes/theme.inc (1125)
in theme called at /data/code/cores/drupal/drupal-7.54/includes/common.inc (6052)
in drupal_render called at /data/code/cores/drupal/drupal-7.54/includes/common.inc (6059)
in drupal_render called at /data/code/cores/drupal/drupal-7.54/includes/common.inc (6059)
in drupal_render called at /data/code/cores/drupal/drupal-7.54/includes/common.inc (6059)
in drupal_render called at /data/code/cores/drupal/drupal-7.54/includes/common.inc (6059)
in drupal_render called at /data/code/cores/drupal/drupal-7.54/includes/common.inc (6059)
in drupal_render called at /data/code/cores/drupal/drupal-7.54/includes/common.inc (6153)
in render called at /data/code/profiles/express/express-2.3.5/themes/expressbase/templates/page.tpl.php (107)
in include called at /data/code/cores/drupal/drupal-7.54/includes/theme.inc (1526)
in theme_render_template called at /data/code/cores/drupal/drupal-7.54/includes/theme.inc (1208)
in theme called at /data/code/cores/drupal/drupal-7.54/includes/common.inc (6052)
in drupal_render called at /data/code/cores/drupal/drupal-7.54/includes/common.inc (5914)
in drupal_render_page called at /data/code/cores/drupal/drupal-7.54/includes/common.inc (2748)
in drupal_deliver_html_page called at /data/code/cores/drupal/drupal-7.54/includes/common.inc (2621)
in drupal_deliver_page called at /data/code/cores/drupal/drupal-7.54/includes/menu.inc (542)
in menu_execute_active_handler called at /data/code/cores/drupal/drupal-7.54/index.php (21)
```

**Comment by owenmorrill** [comment]
kreynen 
[9:23 AM] 
you could point it at the RAVE example feed locally and then add an invalid character or remove a < to see the behavior


[9:24] 
What we really need there is to just check that the feed is valid before trying to parse it and then watchdog an error for an invalid feed vs. letting PHP fail

**Comment by alexfinnarn** [comment]
When testing this locally, the first thing I notice is that the check for a valid RSS URL doesn't work. 

![screen shot 2018-03-06 at 12 43 15 pm](https://user-images.githubusercontent.com/3640707/37054766-f99fc0cc-213c-11e8-9e76-58391d56883c.png)

After I turn off validation for the URL field, I can see that the feed does work as expected. 

![screen shot 2018-03-06 at 12 43 27 pm](https://user-images.githubusercontent.com/3640707/37054777-0bad5932-213d-11e8-9118-e9e948652244.png)

So a custom validation handler should be added to this PR to handle URL checking.

The second issue I see is that the RSS block still displays with the block title but no error or any message to the end-user. 

![screen shot 2018-03-06 at 12 51 51 pm](https://user-images.githubusercontent.com/3640707/37054839-437d6e56-213d-11e8-8b62-5ef43ebc6a6d.png)

Some message should be shown to them rather than a blank block. This probably also goes for any other block relying on an external service. They all should have fallbacks for when network error happen. 

I don't think the PR and code change address this issue, it would only potentially cover it up more with the exception that has less data than the error message posted above.

**Comment by owenmorrill** [comment]
The cu_rss_block form validation is only checking for a 200 as far as I can tell. We could change it up to look for other responses--make sure it's not a 404, maybe?
