### ISSUE TITLE
As a SO/CO I would like to enable page translation using the Google translation API

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1072]
## Context

In 2017 we have three requests for site content in other languages. Here is the latest request which offers an integrated solution that would not involve rewriting code for i18n.
```
Web Express Support EXP-6483
Good Morning!
We are beginning to plan the web presence for the work the Front Line Service Employee task force is doing on behalf of Kelly Fox for front line employees. There will be resources available on the web and we need to accommodate individuals that need information in Spanish, Lao, Nepali, Chinese, and Tibetan. The easiest and by far most cost efficient way to do that is to use the google website translate plugin found here: [1]https://translate.google.com/manager/website/ Is this something that can be incorporated into web express pages? Figuring it probably wouldn’t work, I tried it anyway and the code got scrubbed out.
Thank You, 
Megan
----------------------------------------------------------------------------------------
[1] https://translate.google.com/manager/website/
```

Other requests
Web Express Support EXP-5912
Aquetza: Site content in Spanish

Web Express Support EXP-5244
Korean Graduate Students Association

Site that is written in both English and Spanish
http://www.colorado.edu/rioverdearchaeology

**Comment by kreynen** [comment]
What the sites like http://www.colorado.edu/rioverdearchaeology is currently doing isn't something we can support using Drupal's normal i18n support.  The content of nodes and blocks are both English and Spanish.  To translate parts of text like that we'd need to implement something like http://ckeditor.com/addon/xdsofttranslater

That plugin would add a button to the editor that integrates with Yandex Translate API, Google Translate API and Bing Translate API, but it isn't open source.  It costs $49 for unlimited sites http://js.plus/products/translator/purchase.

I've worked on several sites that leverage Drupal's support for setting the default language for the UI like http://www.okv.se/user where the normal username/password text is in Swedish.  This seems trivial for the form, but becomes MUCH more important for validation.

I've also worked on sites that link the English and Spanish nodes so [that there is a workflow that shows that the content is not in sync](https://www.drupal.org/docs/8/multilingual/translating-content).  https://www.boulderhousing.org/ used to have a traditional i18n integration, but they've gone to only translating a few nodes.  

This is MUCH easier to support it you aren't concerned with features that end users see like webforms.  

Another way to support partial translation using the Google API is https://www.drupal.org/project/tmgmt, but I think that the WYSIWYG approach is going to be much easier to maintain. 

Downsides/limitations to partial translation approach include:
- meta tags are not translated so this has limited SEO benefit
- there are limits to characters that can be used in the menu.  Korean is not going to be displayed properly
- only left to right languages are supported.  Can't display Arabic or Hebrew.

Since users can already translate parts of nodes and blocks themselves using a variety or tools, I'd rather not add support for this into Express.  It's a slippery slope.  We really don't have the resources to support truly multilingual sites.
