### ISSUE TITLE
Convert cu_livetream_embed module to an Embed Template

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1119]
## Context

The module currently uses a shortcode to embed the JS needed to load the livestream. Users could use blocks and the design tools to accomplish the same look and feel as if they used a shortcode. 

https://github.com/CuBoulder/cu_livestream_bundle/blob/master/modules/custom/cu_livestream_embed/cu_livestream_embed.module

Along with some other shortcodes, like maps and videos, I think they can be moved to embed templates to have a more consistent approach with embedding third-party code on Express sites.

**Comment by kreynen** [comment]
I may blow your mind here... why not create a shortcode that allows users to reference any embed template since the embed render can be called when rendering the page?  Then extending this to its logical conclusion, build et_shortcode support to a WYSIWYG button that can add any et type the user has access to?
