### ISSUE TITLE
As a SO/ CE I would like to have faculty publications pulled from FIS

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1122]
## Context

Sebastian Kopf <Sebastian.Kopf@colorado.edu> is inquiring about using web express for the Geological Sciences department and has asked about this particular feature

He would like faculty publications pulled from ORCID in real time, he built a simplified demo here: https://cugeology.github.io/geoldev/people/faculty/templeton/

**LIST OF SITES WITH PUBLICATION LISTS:**

- https://itll.colorado.edu/about_us/publications/
- https://www.colorado.edu/faculty/summers/publications (experts page  https://experts.colorado.edu/display/fisid_113151)
- https://www.colorado.edu/faculty/argrow/publications (experts page https://experts.colorado.edu/display/fisid_102860)

**Comment by kreynen** [comment]
I reached out to Alex Viggio <Alex.Viggio@Colorado.EDU> and the group that runs https://experts.colorado.edu/.  I'm Alex's group can follow up with Identity Management to see if the ORCID can be added as an optional element of the user object.  If not, we can add the fields directly to the Person nodes.

**Comment by sebkopf** [comment]
Thanks, ORCID and/or CUBES integration generally would be really fantastic. I mostly suggested ORCID because it is public and many researchers already maintain their publications there (and then import into CUBES for annual FRPA). The ORCID API is quite well-developed so once ORCID ID is known (and FIS has them for all active faculty) this could be imported statically on a regular basis or dynamically parsing the orcid json data (you probably saw the example script at https://cugeology.github.io/geoldev/js/orcid.js). For CUBES I heard from Matt Ramey Matt.Ramey@colorado.edu that a web API is in the works.

**Comment by aviggio** [comment]
Hi @sebkopf bringing this to the attention of the FIS team that manages CUBE, CU Experts, and the ORCID integration/data that you mention. Our team's current iteration ends June 20th, so might be a couple of weeks before we get back with an update or more questions, but it's great to hear about this use case! Also coming up to speed with how the Web Express team manages their process, so might have some basic questions. For example, what do you or @kreynen envision being the deliverable(s) here? A new custom Drupal module or other? Do you currently access any data from CU Identity Management systems?

**Comment by sebkopf** [comment]
Hi @aviggio, I assume this would have to be a custom module but don't really know Drupal well enough to make any well-informed assessment regarding implementation. The use case is quite specialized to academic institutions since ORCID is not used much outside academia and the academic publishing industry. That said, most academic institutions could benefit for all faculty pages with automatic publications import from ORCID.

Regarding data from CU Identity management system, not speaking for WebExpress but for our department, we received some data on faculty information from Kristina Cizmar and pull additional information from cu experts with a custom script that parses the HTML output of the experts.colorado.edu website (not a very elegant solution but works for our purposes at the moment) that was shared with Liz Tomich.

**Comment by jwfuller** [comment]
Need timeouts and kill switches to mitigate any performance issues, like we want for all 3rd party API integrations

**Comment by kreynen** [comment]
[CUBE-fields-for-INSTAAR-2018-02-13.pdf](https://github.com/CuBoulder/express/files/1724742/CUBE-fields-for-INSTAAR-2018-02-13.pdf)

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/cu_faculty_publication_bundle #13](https://github.com/CuBoulder/cu_faculty_publication_bundle/issues/13) via [**ZenHub**](https://www.zenhub.com/)
