### ISSUE TITLE
As a SO/CE I want to display content in expandable/collapsed sections, such as accordions or tabs

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1151]
## Context

The Quicktabs module has been more difficult to maintain and does way more than we need it to. It's time to make our own.

By making our own we can make this more accessible and more efficient. We can also stop them from being nested.

## Possible Solution
Making our own custom block type that includes a simple text field (because you shouldn't have to make a block if all you want to have is some text) and an entity reference field to include other blocks.

## Screenshots
![screen shot 2017-06-13 at 12 01 43 pm](https://user-images.githubusercontent.com/349713/27097065-4e842cf6-5030-11e7-94ad-9fca29d2a7bf.jpg)
![screen shot 2017-06-13 at 12 02 52 pm](https://user-images.githubusercontent.com/349713/27097080-579cdc34-5030-11e7-9bc1-f4eae925767c.jpg)

**Comment by kreynen** [comment]
I've added the AUL Review tag because some of the custom quicktab implementations have been flagged as problematic.  Specifically https://living.colorado.edu/sustainability and https://living.colorado.edu/explore-your-options.  I think the biggest issue with https://living.colorado.edu/sustainability is that the quicktab loads without any items open and once it's open, it can't be closed.  That issue isn't limited to HDS.  We'd need to write some reporting to figure out how many users have configured a quicktab this way, but more important is to figure out if we want to allow this with expandables.

**Comment by jwfuller** [comment]
Need to make sure that we prevent recursion or extreme depths. IE, tabs inside tabs inside tabs
