### ISSUE TITLE
Webforms with file fields fail validation on file type

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1420]
## Context

New webforms created since 2.6 with file fields will fail validation because the values aren't set correctly.

## Process

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Click Add Content
3. Click Webform
4. Make a form with a file field set to accept jpg images
5. Click save
6. When viewing the form, the field should display it accepts jpg images and it should allow you to upload files.

## Expected result

The form should show the file extensions that it accepts and uploading a file should work.

## Current result

Form shows numbers instead of file extensions. File uploads fail validation.

**Comment by jwfuller** [comment]
Introduced in https://github.com/CuBoulder/express/pull/1266

**Comment by cathysnider** [comment]
I am not seeing this problem in TST or PROD. Both sites at 2.6.1; neither form shows numbers instead of file extensions; both accept a JPG w/o any trouble. (Both reject JPGs over 2MB, as they should.)
https://www-test.colorado.edu/sandbox/cathy/node/506 
https://www.colorado.edu/p1f4bca2b935/node/554

![screen shot 2017-08-25 at 1 02 39 pm](https://user-images.githubusercontent.com/638275/29728684-37a82f06-8996-11e7-9fc7-29df292b1978.png)
