### ISSUE TITLE
Bug: A Site Owner should be able to invite users to Digital Campaign Manager role

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#1474]
@cathysnider commented on [Wed Aug 30 2017](https://github.com/CuBoulder/atlas/issues/360)

## Context

In a site with the Digital Campaign bundle enabled, the Digital Campaign Manager role is not available to site owners. I.E. they cannot invite someone to join the site as a Digital Campaign Manager.

## Process

Enable Digital Campaign bundle.
Attempt to invite a user to join site as a DCM. 

## Expected result

The Role should be available as a choice

## Current result

The Role is not available as a choice.

## Possible Fix

Make it available

## Screenshots

![asdev](https://user-images.githubusercontent.com/638275/29880487-19138392-8d65-11e7-9144-99c3b4798895.jpg)
![assiteowner](https://user-images.githubusercontent.com/638275/29880488-19169a32-8d65-11e7-8b6a-d5213a958061.jpg)

----

## Links to Examples

* [Master of Science in Org Leadership](https://www.colorado.edu/p15a3825272b/)

**Comment by kreynen** [comment]
That is by design and we went over this multiple times in Monday meetings, emails, Slack and even had a 1 hour meeting with other members of  Strategic Relations about this... but somehow it was still documented incorrectly at http://www.colorado.edu/webcentral/tutorial/v2/campaign-manager-role.

You can't be invited as a Campaign Manager.  If users don't want to give users any other editing permissions, invite them as Edit Own and just don't give them authoring permissions on any nodes. 

I've updated the documentation.
