### ISSUE TITLE
Social Media error message: "email address is not a valid URL for email type"

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1479]
## Context

When adding link type 'email' to Social Links block, an email address is rejected as an invalid URL

## Process

1. Enable Social Media bundle 
2. Go to 'Blocks' and add a Social Links block. 
3. Choose link type 'Email' and enter an email address such as sniderc@colorado.edu into URL field
4. Save and/or click 'add another item' (this makes system check the URL field)
5. Get message 'The value of sniderc@colorado.edu provided for URL is not a valid URL.'

## Expected result

I expect the system to accept email addresses as valid

## Possible Fix

The system wants email addy's to be prefaced with 'mailto:' -- however, most site builders and content editors do not know this fact about html. 

* Add some explanatory text about this
* or automatically populate field with 'mailto:' when Type Email is chosen

## Screenshots

![sociallinksbug](https://user-images.githubusercontent.com/638275/29937727-c1e918f4-8e43-11e7-9048-25324614019b.jpg)

----

## Links to Examples

* [Webform Page](https://www.colorado.edu/p1/721)
* [Drupal issue](https://drupal.org/node/721)

**Comment by jeor0980** [comment]
After some research I have found that the issue is in the [cu_social_links_collection_item_presave() function](https://github.com/CuBoulder/express/blob/3c1c695672e6f9cd6bdd83bd14f5d8fe3bd3f2e6/modules/features/cu_social_links/cu_social_links.module#L46). When the code checks if $submitted_url doesn't start with the characters 'mailto:' it should append them to $submitted_url, but this case can't be reached because of the presave behavior on collections, $submitted_url isn't updated unless it is correctly formatted.

**Comment by kreynen** [comment]
Since the current alters and validation remove the mailto: even when it's entered correctly, the result is users see this error on every edit even when they correctly enter the mailto:email the first time.  Categorizing as a bug.
