### ISSUE TITLE
BUG: Countup shortcode sometimes counts to a different number

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1498]
## Context

Some numbers aren't processed correctly and the countup can be off by 1.

For instance: 506

## Process

[ordered list the process to finding and recreating the issue, example below]

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Click Add Content
3. Click Basic Page
4. Enter [countup] 506[/countup] in the body field
5. Click save

## Expected result

It should count up to 506.

## Current result

It counts up to 505.

**Comment by owenmorrill** [comment]
PR has been merged.

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [ ] Countups integers that didn't, now do (including 506 and 123,456,789)
- [ ] Other countups continue working
- [ ] Other shortcodes continue working

Fail because two countup no longer work: the Dollar Amounts countup and the Decimal countup 
https://www-dev.colorado.edu/p1e3e27f8eb6/amazing

Note: The Time countup never worked, so I'm not going to fail this because of that. 

https://www-dev.colorado.edu/p1e3e27f8eb6/

**Comment by kevincrafts** [comment]
In looking at Cathy's site, the decimal had an extra space at the end, causing it to count differently - removing the space makes it work properly. The dollar sign should be placed outside of the shortcode. Moving the dollar sign makes it work properly.

**Comment by cathysnider** [comment]
Per Kevin's comments, the fix passes.
