### ISSUE TITLE
As an anonymous user, I'd like the cursor to focus in the Search Box when I click 'Search'

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1542]
From client: "Here’s a little request that I think would make a lot of people’s lives easier. If, when the the search icon is clicked on a page, could the cursor/insertion point be placed into the search field? I have the expectation from lots of other sites that it should do this, but then I forget and start typing and then curse the heavens when I what I’ve typed is nowhere to be found. ;) "

**Comment by kevincrafts** [comment]
We have a PR for this if only one type of search is available. https://github.com/CuBoulder/express/issues/1404

We don't focus on the search box when there are multiple options because from an accessibility perspective we thought it was important to focus to the search options because a user might enter different search terms depending on what the options are.
