### ISSUE TITLE
Add Top 404 block to SEO Dashboard

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1629]

**Comment by cathysnider** [comment]
https://www-dev.colorado.edu/p1e466c6a04d/

**Comment by cathysnider** [comment]
Obviously, all the sites that have the Google Analytics Reports enabled need to be reviewed.

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/express/pull/1764

**Comment by alexfinnarn** [comment]
This PR doesn't "Add Top 404 block to SEO Dashboard" since the "google_analytics_reports" module isn't included anywhere.  On a site install or update, I don't get a 404 block on the SEO Dashboard.

**Comment by owenmorrill** [comment]
![feature1629-blocker](https://user-images.githubusercontent.com/5008565/36558940-e385436a-17c9-11e8-8783-a0a7e6decd91.png)

We need google api keys for this to connect back to our analytics account.

**Comment by owenmorrill** [comment]
![top404block](https://user-images.githubusercontent.com/5008565/36562402-274a8f2e-17d4-11e8-8c4d-558aed985ec3.png)


Need to configure your own analytic reports API info.

**Comment by alexfinnarn** [comment]
On install of the SEO Bundle, I see `Imported 496 Google Analytics fields.` Is that necessary? Seems like a lot of fields, although they don't appear to be Drupal fields. If there is some query or function that takes into account all of those fields, I would think it would be slower due to all the fields looped through.

The PR needs to enable the module in an update hook.

I do see the 404 block and get to the instruction page. Am I supposed to follow the instructions on the next screen? 

It's interesting to have instructions in the Drupal UI, but should those go into a HelpScout article instead? And/or add a help link...seems like this needs some check from Emily before merging.

**Comment by alexfinnarn** [comment]
Also, there are a couple CC issues to fix.
