### ISSUE TITLE
backstretch url is http event though set to https, causing mixed content warning over https

### ISSUE THREAD

**Issue by johnquest** [CuBoulder/express#1707]
## Context

Clearing caches doesn't update the link to the backstretch image. When the image is added, the http link is displayed and people are copying it into the sitewide context and backstretch reaction. But when editing it to https, change doesn't take effect.

**Comment by kreynen** [comment]
I'm not sure what's happening here since what is written into the page is in the JQuery variables...

`"backstretchURL":"\/umc\/node\/202\/attachment" `

If you look in the Context configuration, the URL that was entered in https://www-stage.colorado.edu/umc/node/202/attachment which is no longer a valid DNS entry.

Related to https://github.com/CuBoulder/express/issues/1818
