### ISSUE TITLE
Add validation warning when users include an absolute URL

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1767]
## Context

This stems from [EXP-8437] 

99% of the time, an absolute URL entered into the **URL Path setting** field is a mistake and results in a very long, confusing URL since the browser tries to convert http:// into https%3A//.

When the user fixes the problem, a redirect is created that will eventually expire, but we could avoid all of that if we just ask users who are using an absolute URL on new nodes if that's really what they want to do.  In a few edge cases, it is... but 99% of the time, it isn't.

![create_basic_page___environmental_center](https://user-images.githubusercontent.com/385234/34389495-3195cd2c-eaf7-11e7-9dfa-509a42a3018f.png)

**Comment by cathysnider** [comment]
In addition, 

People do not understand that they should not enter the domain and site name, so they enter the full URL as it will appear to their visitors. Can we change the form so that the domain and site appear before the input field, the way they appear when setting up redirects -- admin/config/search/redirect/add 

![domainandsite](https://user-images.githubusercontent.com/638275/34391038-c1195d02-eb00-11e7-8c94-f821f3ba483e.jpg)

**Comment by alexfinnarn** [comment]
The connected PR looks for a scheme and then periods in the path returned by `parse_url()`. If either exists, then the user gets an error message. 

To turn this into a warning, I think maybe some variable should be used rather than complicating how nodes are saved with a multi-step UI validation process.

The messages will change, but they are set up for debugging purposes now.

**Comment by alexfinnarn** [comment]
Should add https://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7.x#field_prefix to accomplish "the domain and site appear before the input field".

**Comment by cathysnider** [comment]
Test branch: https://www-dev-new.colorado.edu/p1b40f21b798/

**Comment by cathysnider** [comment]
Consulted with UI team about error messages. They are much too cryptic as written. Most users don't know what these sentences mean. 
![screen shot 2018-07-02 at 2 42 45 pm](https://user-images.githubusercontent.com/638275/42185702-22471008-7e07-11e8-9dfc-94c0ff4356db.png)

The UI team feels that most users do not know what a relative path is. All that needs to be said is "Please enter page name only in the URL alias field. Do not include the site name."

**Comment by alexfinnarn** [comment]
closing due to merged PR and QA pass.
