### ISSUE TITLE
Linkchecker error

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#1812]
## Context
Occurefd 16 times on the `next` site https://rpm.newrelic.com/accounts/1437680/applications/34128397/traced_errors/29047d2a-f7d7-11e7-9373-0242ac110010_0_2217/similar_errors?original_error_id=29047d2a-f7d7-11e7-9373-0242ac110010_0_2217&tw%5Bend%5D=1515789277&tw%5Bstart%5D=1515785677
```
ArgumentCountError: Uncaught exception 'ArgumentCountError' with message 'Too few arguments to function linkchecker_analyze_links_submit(), 0 passed in /data/code/profiles/express/express-2.8.2/modules/features/cu_linkchecker/cu_linkchecker.module on line 47 and exactly 2 expected' in /data/code/profiles/express/express-2.8.2/modules/contrib/linkchecker/linkchecker.admin.inc:351

Sample stack trace
in linkchecker_analyze_links_submit called at /data/code/profiles/express/express-2.8.2/modules/features/cu_linkchecker/cu_linkchecker.module (47)
in cu_linkchecker_analyze_form_submit called at /data/code/cores/drupal/drupal-7.56/includes/form.inc (1520)
in form_execute_handlers called at /data/code/cores/drupal/drupal-7.56/includes/form.inc (904)
in drupal_process_form called at /data/code/cores/drupal/drupal-7.56/includes/form.inc (386)
in drupal_build_form called at /data/code/cores/drupal/drupal-7.56/includes/form.inc (131)
in drupal_get_form called at /data/code/cores/drupal/drupal-7.56/includes/menu.inc (527)
…execute_active_handler called at /data/code/cores/drupal/drupal-7.56/index.php (21)
```

**Comment by kreynen** [comment]
I can't see how this is working at all since nothing is being passed to linkchecker_analyze_links_submit while it is expecting the form and form state.

https://github.com/CuBoulder/express/blob/dev/modules/features/cu_linkchecker/cu_linkchecker.module#L47

https://github.com/CuBoulder/express/blob/d1d58b1cb26d402a9e7f4fa1a8913a148add553e/modules/contrib/linkchecker/linkchecker.admin.inc#L313
