### ISSUE TITLE
Help Scout Articles don't render step headings when displayed in Modal

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1825]
## Context

http://websupport.colorado.edu/article/67-group-collaboration-ideas

![screen shot 2018-01-18 at 2 59 09 pm](https://user-images.githubusercontent.com/385234/35124077-ff81fea6-fc61-11e7-97fe-14acbf030245.png)

**Comment by kevincrafts** [comment]
I did not realize that Help Scout tutorials are loaded directly into the beacon rather than opening a new window.  There is no configuration option to make it do that.  Also, the custom code that can be added to Help Scout (css/js) is not loaded into the beacon, so the styling we are doing to make those numbers does not work.  Since the beacon content is an iframe, it could be difficult to try to modify their iframe from code in Express.

**Comment by kevincrafts** [comment]
We have decided to not use the additional custom scripting/styling for these and instead use markup (decision lists) similar to what HelpScout uses. New tutorials will use this markup. Existing tutorials will need to be updated.
