### ISSUE TITLE
Bug: Newsletter not displaying articles; taxonomy is missing image

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1845]
## Problems

Newsletter is not displaying articles, not in web version or email version. 

Newsletter taxonomy does not have the image logo uploade

https://www-test.colorado.edu/p1bde2411132/admin/structure/taxonomy/newsletter

**Comment by kevincrafts** [comment]
https://www-test.colorado.edu/p1bde2411132/newsletter/portfolio/january-2018

Fixed  the article displaying issue with https://github.com/CuBoulder/cu_newsletter_bundle/releases/tag/1.2

The image logo field is only available to developers because we don't allow users to upload their own logos.  The logos are VERY limited in use and there are no plans to expand this.
