### ISSUE TITLE
Populate 4 levels of Orgs with data from cu_campus_directory_bundle

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1915]
## Context

We are limited by the field types Help Scout allows in Conversations and Reporting.  

The hope is that a Conversation started about http://www.colorado.edu/webcentral would be able to look up to owner of that site and populate that 4 levels of Organization fields with Strategic Resources and Support > Strategic Relations > Marketing Services > Web

![populate organization](https://user-images.githubusercontent.com/385234/36121252-d1ade350-1002-11e8-84df-a27a990204f2.png)

I looked at populating the dropdown field type with a fake hierarchy like...
Strategic Resources and Support 
- Strategic Relations 
-- Marketing Services 
--- Web

That would be more user-friendly than 4 fields, but the goal is that a user will never need to fill these out.  The fake hierarchy doesn't work well on the reporting end.

![org levels](https://user-images.githubusercontent.com/385234/36121362-24c86bd2-1003-11e8-8762-d2cbf1fdb6c9.png)

The 4 fields requires @jbertrand to know the exact strings of the org names needed to build the reports, but they will be able to get that from the directory.

**Comment by alexfinnarn** [comment]
I found https://www-test.colorado.edu/directory with the https://github.com/CuBoulder/cu_campus_directory_bundle bundle on it, but I don't know where a full list of the directory resides.

I think the directory bundle needs an endpoint with a list of top-level orgs and their children so that any site can know what it's directory structure looks like. Then it is easy to put that data into the Beacon when a support request is created. Webcentral could post new directory information to each site once a day to keep the site information up-to-date.

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/directory #18](https://github.com/CuBoulder/directory/issues/18) via [**ZenHub**](https://www.zenhub.com/)
