### ISSUE TITLE
Link Checker is currently throwing Errors

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1995]
## Context

Go to Link Checker on any Web Express site with SEO bundle enabled and click button 'Analyze content for links'
https://www.colorado.edu/engineering/admin/settings/seo/linkchecker-analyze
https://www.colorado.edu/conferenceservices/admin/settings/seo/linkchecker-analyze
https://www.colorado.edu/registrar/admin/settings/seo/linkchecker-analyze
https://www.colorado.edu/lab/vernerey/admin/settings/seo/linkchecker-analyze
https://www.colorado.edu/designforamerica/admin/settings/seo/linkchecker-analyze

You will get the Drupal Drop Error Screen.

## Screenshots

![drupaldroperror](https://user-images.githubusercontent.com/638275/37052159-b64ba518-2135-11e8-931d-c27d4bde4dc9.jpg)

----

**Comment by alexfinnarn** [comment]
Yeah, we already know about this issue: https://github.com/CuBoulder/express/issues/1812

That code change should fix the issue.; however, it would be nice to have the particular error message received rather than a picture of a white screen. 

The preferred way of doing that is to look at logstash, but you can also briefly enable the "dblog" module to get the error message and then turn it off.

Can you confirm this is still an issue in the dev branch?
