### ISSUE TITLE
SAML Redirects result in an Access Denied

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2053]
## Context

![screen shot 2018-03-22 at 8 55 44 am](https://user-images.githubusercontent.com/385234/37778199-f594b2de-2dae-11e8-8d8f-1335b83a99be.png)

One option would be to use the SAML module's ReturnTo cookie value in https://github.com/CuBoulder/express/blob/feature/1784/modules/custom/express_dashboards/express_dashboard_user/express_dashboard_user.module#L159

**Comment by alexfinnarn** [comment]
I think this is fixed on https://www-test.colorado.edu/p1d0d212264e. I redirected the request to the same route since session information is generated somewhere during the request but not available when checking for admin page access. 

To test:

1. Login to https://www-test.colorado.edu/p1d0d212264e/saml_login
2. Click on a few menu items for good measure.
3. Click the logout link.
4. Go directly to an admin page, e.g. https://www-test.colorado.edu/p1d0d212264e/admin/reports
5. See that you are logged in with no access denied message.

In the Drupal backend, I still see access denied messages, so I'm not sure if this is the final solution, but it worked for my account.

![screen shot 2018-03-23 at 9 20 52 am](https://user-images.githubusercontent.com/3640707/37837858-01bdb088-2e7c-11e8-8560-d996fa5c3e83.png)

**Comment by alexfinnarn** [comment]
With the "osr-test-owner" I needed to login in twice. The first time I got a fedauth error. I was placed in the `authmap` table but not on the user screen with "Last Access". The second login worked. I also tried to go to "admin/modules" and did see a proper "Access Denied" without any redirect loop.

**Comment by alexfinnarn** [comment]
closing due to merged in PR.
