### ISSUE TITLE
Quicktabs Shows Up Under Structure/Permission Denied

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2231]
There seem to be some Quicktabs permissions that don't get captured.

![screen shot 2018-04-27 at 4 24 05 pm](https://user-images.githubusercontent.com/3640707/39387562-7c7e0c92-4a37-11e8-9151-605bb892dec4.png)

The tutorial says to add it via the Structure menu https://www.colorado.edu/webcentral/tutorial/v2/create-quicktabs

I get an "Access Denied" on the dev branch locally when going to "admin/structure/quicktabs/add".

That's all I know...

**Comment by cathysnider** [comment]
This is proper functionality. The Quicktab section can be reached, but no new Quicktabs can be added. Currently existing QTs can be edited. This is necessary because because some of our users still have Quicktabs on their site. At some point, we are going to have to strongarm them into switching their QTs to Expandable Blocks. 

I've written a Behat test checking this.
