### ISSUE TITLE
Improve admin/reports for inactive users to delete users

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2418]
## Context

Not really sure what criteria we should be using to identify inactive accounts.

**Comment by owenmorrill** [comment]
I think the two pieces of info that would be most helpful to SOs and SEs about inactive accounts would be: 

- If the user hasn't logged in for over 365 days.
- If the account has never logged in or if they've never contributed (created or edited a page)

I don't think SOs will be too concerned unless they need to remove the account--otherwise, what are they looking for with an inactive account? 

I'm thinking a full year because there are users who only log in once a year to update events or pages. 

No content means it's really simple to remove their account.

**Comment by kreynen** [comment]
I fixed some of the VBO permission issues in https://github.com/CuBoulder/express/issues/2889, but users still can't bulk delete users.  Only bulk block.  This doesn't even work with uid 1, so something is altering that core functionality.  This worked a few months ago because bulk deleting users without a role on the homepage was one of the things I did to test the db io on the new servers.  Is this related to https://github.com/CuBoulder/express/issues/2887 It might be easier to write our own bulk delete than to try to figure out and fix what's happened.
