### ISSUE TITLE
Broken Links report has lots of "permission restrictions deny you access" even for Developers

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2563]
1. Sign in to Beta Site on New Prod as developer.
2. Go to Broken links report.
3. View all the messages

Broken Link checker report is sometimes filled with "Permission restrictions deny you access to this broken link." even when signed in as developer.

Examples: 
https://www-prod-new.colorado.edu/business/user?destination=admin/reports/linkchecker
https://www-prod-new.colorado.edu/graduateschool/user?destination=admin/reports/linkchecker

**Comment by jeor0980** [comment]
Two things: 

1. Rebuilding the broken links report on a site on new Prod seems to fix this issue.

2. I think that this issue will fix itself. 

I think the reason we're seeing this error is because the links that are stored in database do not match the new prod site's current url pattern _https://www-prod-new.colorado.edu/business vs https://www.colorado.edu/business_, caused by cloning the site.

When linkchecker is checking for access to the nodes with the broken links it does a check on the urls that are on old prod and not the current site and that's why get this error.

**Comment by jeor0980** [comment]
Linkchecker report will be cleared and re-populated once sites are launched on new prod. https://github.com/CuBoulder/atlas/issues/481
