### ISSUE TITLE
Campaign Mgr role is not exposed to SOs

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2583]
The Campaign Manager role is not showing up as one of the Add On Role choices. 

1) Sign on as a Site Owner to one of the Beta Sites that has Digital Campaign Manager bundle enabled (See list below: )

2) Go to User page and edit a person-- /user/xxx/edit

3) Note that the Campaign Manager role is not appearing as one of the Add On role choices. 

Examples:
https://www-prod-new.colorado.edu/menv/
https://www-prod-new.colorado.edu/
https://www-prod-new.colorado.edu/today/
https://www-prod-new.colorado.edu/business
https://www-prod-new.colorado.edu/music
https://www-prod-new.colorado.edu/law

![addonroledc](https://user-images.githubusercontent.com/638275/41556518-42fde480-72f8-11e8-90bd-281650e4c5aa.jpg)

Weirdly these sites do have it:
https://www-prod-new.colorado.edu/summer/

**Comment by jeor0980** [comment]
Permissions need to be rebuilt for that to populate.

**Comment by kreynen** [comment]
The issue is the update hook in https://github.com/CuBoulder/cu_digital_campaign_bundle/blob/master/cu_digital_campaign_bundle.install#L24 hasn't been deployed

Both prod old and new are on https://github.com/CuBoulder/cu_digital_campaign_bundle/commit/01df5d5fdb07f7395aeff131a55d49bcc7426555 from Oct 10, 2017.
