### ISSUE TITLE
CU_LDAP: cu_ldap_cron not actually running or updating users.

### ISSUE THREAD

**Issue by owenmorrill** [CuBoulder/express#2598]
This means no display, affiliation, or last name is populated on cron run.

**Comment by kreynen** [comment]
With Elysian, cron is now run on install so new installs should have displaynames and last_names for all users in LDAP.  If the user is in LDAP, but the values aren't populated for users we are populating both the dsipdisplaynames and last_name w/ the account name.  So something like osr-test-owner will appear everywhere.

If cron runs when LDAP isn't available (like when you're at home or if LDAP is down), I've added code to skip the updates.  We didn't need that for the on login update because the login depended on LDAP being up.  But with cron and SAML, we can't assume LDAP is up.

![content___university_of_colorado_boulder](https://user-images.githubusercontent.com/385234/42063434-e4b33da4-7aee-11e8-80d9-e4e74c3628ff.png)

To force cron, run `drush vset cu_ldap_ping_time 0` and then go to admin/config/system/cron and force run the cu_ldap cron.

We need to test this on a laptop when it can connect to LDAP and when it can't.  

I've opened https://github.com/CuBoulder/express/issues/2681 to address uids 0 and 1.

**Comment by alexfinnarn** [comment]
Right now, I cannot log in via LDAP locally, at least with `$_SERVER['OSR_ENV'] = TRUE;` in my settings.php file. However, I can see that LDAP works to get my full name on site install.

<img width="1081" alt="screen shot 2018-06-29 at 11 25 40 am" src="https://user-images.githubusercontent.com/3640707/42101076-f539a702-7b8f-11e8-9b46-e7231103e05a.png">

And then with the current dev branch, there are no realnames on install for me.

<img width="1174" alt="screen shot 2018-06-29 at 11 30 15 am" src="https://user-images.githubusercontent.com/3640707/42101097-0441bf96-7b90-11e8-888e-4d41144cec04.png">

**Comment by alexfinnarn** [comment]
Okay, so I installed a site on the feature branch, and I got the realnames with links.

<img width="1210" alt="screen shot 2018-06-29 at 11 44 43 am" src="https://user-images.githubusercontent.com/3640707/42101779-22b7dfb2-7b92-11e8-97e0-f2a598ade025.png">

Then I ran the cron job, and I saw no differences.

<img width="1129" alt="screen shot 2018-06-29 at 11 45 29 am" src="https://user-images.githubusercontent.com/3640707/42101790-2e77aa8a-7b92-11e8-91dc-c95d44ccc12a.png">

Just changing to the dev branch caused the realnames to be lost. I also ran the cron job and the names stayed the same.

<img width="1196" alt="screen shot 2018-06-29 at 11 46 43 am" src="https://user-images.githubusercontent.com/3640707/42101819-49d68f9e-7b92-11e8-8685-ab8d44f7adcd.png">
