### ISSUE TITLE
LDAP bind failure for user userdn=, pass=.

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2639]
## Context

https://www-prod-new.colorado.edu/p1652f78c6a6/admin/people/invite

**Comment by owenmorrill** [comment]
https://www.drupal.org/project/ldap/issues/2985428

**Comment by owenmorrill** [comment]
We think the cu_ldap feature is the problem because the configuration is not the same across different sites. Some of them don't even have directory.colorado.edu configured.

**Comment by owenmorrill** [comment]
It appears that our sites aren't getting the config saved to the db table "ldap_servers" on installation so there's never anything to check against.

We should be saving the config we have directly to the database on installation so that we can use features to check what we have in code against what we have in the database.

**Comment by owenmorrill** [comment]
Updated the d.o ticket: https://www.drupal.org/project/ldap/issues/2985428#comment-12731046

I can definitely confirm that no check is made back to the variable in the database to see if the code has changed in cu_ldap_default_ldap_servers() (the variable is: ldap_authentication_conf).
