### ISSUE TITLE
Improve UI to Encourage Promoting Existing Users

### ISSUE THREAD

**Issue by owenmorrill** [CuBoulder/express#2888]
**Describe the bug**
Now that we offer addon roles, what happens when you invite someone and the click on the invite link in the email while they're already logged in?

**To Reproduce**
Create an invite for a user. Have them log in and then click on the link in the invite email.

**Expected behavior**
Currently, if you click on the link in the invite email while logged in, you'll see: 

`The email "email@example.com" does not match the current user "testuser". The invite role was not granted.`

We want some kind of an error, or a way for Express to realize that person needs the additional role.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kreynen** [comment]
The problem with inviting an existing user to an additional role is that we can't guarantee that the email the SO invites is actually the email associated to the user via LDAP.  While any email address can be used for the initial invite when the user does not exist at all in Drupal, the SO would need to use the same email used by LDAP to promote an existing user through an invite.  

Rather than try (potentially in vain) to get this working through validation, we should change the names of the tabs under /admin/people from `Invite users` -> `Invite new users` and add a new tab for `Promote existing user` that simply provides a lookup for **Which user who you like to promote?** and then sends them to the updated edit UI.
