### ISSUE TITLE
Using user_delete instead of user_cancel resulted in nodes being deleted

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#3061]
This is related to the issue Anseth Group Website reported in https://cuboulder.atlassian.net/browse/EXP-12286

**Comment by kevincrafts** [comment]
Looking through the user_cancel function it seems there is no way to actually remove the user without nodes being deleted.  While you can pass various options to user_cancel, if you want the content to stay the user status only gets set to 0, so they aren't actually removed, just blocked.

If we want to totally remove the user and retain any node content, we probably need to write our own functions to accomplish this, but it does bring up the question of how confusing it could be to have a bunch of nodes and/or revisions that were made by anonymous.  What happens when this is done for multiple staff, meaning multiple items are set to anonymous but you can't tell which one originally belonged to who?
