### ISSUE TITLE
Improve process for removing SRC staff who leave CU

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#3064]
Neither the process used in https://github.com/CuBoulder/express/blob/dev/modules/custom/cu_users/cu_users.install#L213, https://github.com/CuBoulder/express/issues/1027 or https://github.com/CuBoulder/express/issues/3028 works well when a developer or admin user has played a role in creating a site.  

Blocking the user prevents additional edits even if the identikey is reenabled, but requires leaving the user account with the admin or developer role.  Removing the role gives site owners the option of unblocking the user.  

We need to do something about https://github.com/CuBoulder/express/blob/dev/modules/custom/cu_users/cu_users.module#L31 too

We closed https://github.com/CuBoulder/atlas/issues/487, but this might be the way to handle this.

**Comment by alexfinnarn** [comment]
I don't like the idea of putting any of this stuff in the settings.php file if it is supposed to be service-wide. Making changes to the users and roles will take longer than switching symlinks.

I propose a `cu_users_purge_user(string $identikey)` function that takes and Identikey and then runs through some steps to purge the user. 

- sends a watchdog message at each step of the purge with messages like `purging user {'identikey'} - Step 2 - Removing User`
- looks for content based on known tables with `uid` fields indicating the stored data is attached to a user
- transfers the content's ownership to another user TBD

The specific users and roles could be moved out of `cu_users_get_users()` into JSON that is loaded from a file. The advantage here is that the file location can change and hopefully one file could be used on the mounted drives. Or I guess just use the path of the homepage and a file there...idk, I think storing in JSON might make more sense for readability and loading by different consumers.

**Comment by alexfinnarn** [comment]
I made an array of the tables where I found `uid` key in a function called `cu_users_get_content_tables()`. I commented out the revision tables but invites and redirects are two cases that haven't been taken into account before.

```php
  return [
    'node' => 'title',
//    'node_revision',
    'bean' => 'title',
//    'bean_revision',
    'user_external_invite' => 'mail',
    'redirect' => 'redirect',
  ];
```

**Comment by alexfinnarn** [comment]
https://cgit.drupalcode.org/drupal/tree/modules/user/user.module?h=7.x#n2481

If you look in the user module, you'll see that the cancellation process is batched, and so it won't take effect immediately but rather whenever the batch is run. 

This is why I've taken the logic from `_user_cancel` and used that instead of `user_cancel()`.

```php
    case 'user_cancel_reassign':
    case 'user_cancel_delete':
      // Send account canceled notification if option was checked.
      if (!empty($edit['user_cancel_notify'])) {
        _user_mail_notify('status_canceled', $account);
      }
      user_delete($account->uid);
      drupal_set_message(t('%name has been deleted.', array('%name' => $account->name)));
      watchdog('user', 'Deleted user: %name %email.', array('%name' => $account->name, '%email' => '<' . $account->mail . '>'), WATCHDOG_NOTICE);
      break;
```

**Comment by alexfinnarn** [comment]
So, the way it works now...

1. Run `cu_users_purge_user(string $identifier)` to start the process. The identifier is the identikey or realname of the user.
2. If a user is not found by Identikey or realname, then a message is logged `Purging User {@user} - No user found with @type.` and nothing happens.
3. User is checked via `cu_users_user_has_content($user)` to see if they have content. The tables are listed above: `node, node_revision, bean, bean_revision, user_external_invite, redirect`.
4. If user has content, `cu_users_reassign_user_content($user, $reassign_user, $content)` takes the content and reassigns it to a `cu_users_reassign_content_user` by swapping the UID in the DB tables. The anonymous user is used if no reassign user is found.
5. `user_delete($user['uid'])` is used and taken from `user_cancel()' for the reassign case.
6. Delete the user session.
7. Log the purge as being a success. If exceptions or failures, then those are logged.

**Comment by alexfinnarn** [comment]
At the end of the day, the main difference in this PR vs. `user_cancel(array(), $user->uid, 'user_cancel_reassign');` in an update hook are:

- More tables are used when reassigning content. 
- The user to reassign content can be chosen instead of defaulting to the anonymous user
- Any number of steps can be done with this code instead of locking into the Drupal user cancel functions.
- The node module uses the `module_invoke_all('user_cancel', [], user_load($user['uid']), 'user_cancel_reassign');` hook to reassign nodes to the anonymous user and that hook isn't called here.
- This method doesn't use a batch process. I'm not sure what differences that makes.

I don't think removing users should be done in update hooks since that requires a code change to do so and would be slower than running the `cu_users_purge_user(string $identifier)` across sites. Once this code is in the Express profile, then any user can selectively be purged from some or all sites. 

Of course, the LDAP module creates a local account once logged in, but the new user shouldn't have any roles in that case...could be a caveat to explore with an LDAP or user hook or something.

Another thing to note is that `cu_users_create_user(string $user_name, string $role_name, string $realname = '')` in the `cu_users_test` module can be used to create users simply with a role and name.
