### ISSUE TITLE
Image fields with insert enabled are inserted whenever the enter key is pressed in a field

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#826]
## Context

When editing a page that has an inserted image on it, focusing on a field and pressing the enter button can cause additional copies of an image to be inserted into WYSIWYG fields.

## Process

1. Enable News Bundle
2. Create some tag terms
3. Create an Article
4. Add image to photo field and insert into WYSIWYG editor
5. Swith to Tag tab
6. Start typing one of the terms you added in before, and select and enter USING THE KEYBOARD

## Expected result

Using the keyboard enter the taxonomy term should add the term to the term reference field.

## Current result

Using the keyboard to enter the taxonomy term also inserts an additional copy of the image into the WYSIWYG Editor.

## Possible Fix

https://www.drupal.org/project/insert/releases/7.x-1.4

## Screenshots

![ezgif-2-e1a88a3a5b](https://cloud.githubusercontent.com/assets/349713/26377098/25d22a3e-3fcc-11e7-8c47-5a6714abe09f.gif)

**Comment by alexfinnarn** [comment]
"So just implementing this patch would cause other types of problems from the same behavior." I don't know exactly what that means. Can the patch be modified to address the other problems or does entirely new code need to be written?

**Comment by owenmorrill** [comment]
https://www.drupal.org/files/issues/insert-2295507-change_click_to_mousedown.patch

This is corrected in 1.4

**Comment by cathysnider** [comment]
Turns out this problem happens with every content type that has 1) an image insert button and 2) a one-line "input type=text" field -- so, all Basic Pages, Articles and Issues. The solution targets all tags of class 'insert-button', which is only those items that have the Insert Button.  

Acceptance Criteria are pretty simple: 
 - [ ] For each applicable content type, an uploaded image does not get inserted when user places cursor in an input field and hits 'Enter.'

Tested successfully https://www-dev.colorado.edu/p16490ac26a3
