### ISSUE TITLE
As a SO/CE I need to embed the new campus map in my website.

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#883]
## Context

When the new campus map is live, site owners and content editors need to be able to embed this map in their WYSIWYG editor, similar to how they can embed a Google map.

**Comment by cathysnider** [comment]
Verification failed; the map sizes aren't changing as the Google embed code: https://www-dev.colorado.edu/feature/883/map-sizes

**Comment by cathysnider** [comment]
Acceptance Criteria
- [ ] All the shortcodes continue to work
- [ ] The new map is embedded in a basic page. This may be difficult to test since the new map has not yet launched

Test site: http://www-dev.colorado.edu/p1a49bf54a73/ 

Test Fail: The Twitter Share shortcode does not work anymore. http://www-dev.colorado.edu/p1a49bf54a73/share-twitter

**Comment by ekellagher** [comment]
Embed Map tutorial updated
Added a step to embed the campus map
http://www.colorado.edu/webcentral/tutorial/v2/embed-map

**Comment by cathysnider** [comment]
Test page: https://www.colorado.edu/p1f4bca2b935/design-examples/shortcodes 
Results: Looks good. Both Google Map and Campus Map embed properly; and the sizes work: Small, Medium and Large.
