### ISSUE TITLE
Improve use of drupal_http_request

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#909]
## Context

RAVE has been the visual manifestation of problem a number of our service integrations have.  We documented it in https://www.drupal.org/node/2850948 after we mistakenly made a http request to Atlas in each form_alter.

drupal_http_request is also called in https://github.com/CuBoulder/express/blob/dev/modules/custom/cu_rss_block/cu_rss_block.module#L65
While the cache is longer, this can cause the same type of issue we saw with rave_alerts if it is used on a high traffic page.

We know this is used in the Classed Bundle and Drupal core Update project.  

May also need to look at how this is happening in https://github.com/CuBoulder/express/pull/796

**Comment by alexfinnarn** [comment]
For the RSS block, could that be done in a cron job? Theoretically, that would check for new RSS content every twenty minutes. 

You could try charging people for more frequent updates...sounds shoddy, but for now with the limited resources on the servers, limiting to cron tasks could greatly reduce the number of these requests.

**Comment by alexfinnarn** [comment]
We also talked before about having a classes repository that exists elsewhere, say Pantheon, and instead of making all of the REST/SOAP requests, the individual classes sites would make a request to the master classes site.

**Comment by alexfinnarn** [comment]
[https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_http_request/7.x](https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_http_request/7.x)

I would even question using drupal_http_request since that function has a lot of cruft to make it cover all of the bases. This analogy is akin to using Views and the content list queries we've made instead. I'd imagine we could take parts and pieces of this function and suite our needs.
